### ISSUE TITLE
パッケージ名は小文字に統一した方が良い。

### ISSUE THREAD

**Issue by CS-MakotoNinomiya** [CentralsoftTrain2018/OchisCode#1]
パッケージ名は全て小文字に統一するのが一般的です。
Javaを世に送り出した「Sun Microsystems」のコーディングルールだそうです。
クラス名はキャメルケースで命名されるが一般的で、
パッケージが全部小文字、クラス名がキャメルケースだと、初めて大文字が出てきた時にそれがクラスであることが瞬時に判断できる利点があるそうです。

**Comment by t-san** [comment]
ご指摘ありがとうございます。
修正しました。
