### ISSUE TITLE
警告表示からバグの発生個所をつぶす

### ISSUE THREAD

**Issue by koni1212** [CentralsoftTrain2018/OchisCode#15]
![image](https://user-images.githubusercontent.com/27844139/41606441-a9a0f250-741e-11e8-91c1-c573e5c45ad4.png)

警告表示を見ると、使用していないインポートや変数が散見されます。
他処理からコピペしただけということもありますが、バグの発生個所であったりもしますので、
警告の内容を気にかけることも大事です。

**Comment by essences** [comment]
ありがとうございます。
