### ISSUE TITLE
同じ "服" ならば・・・

### ISSUE THREAD

**Issue by matap1623** [CentralsoftTrain2018/OchisCode#2]
RecomClothVo
と
UserClothVo

同じ "服" を表しているので、属性がまったく同じですよね。
○○服 と、△△服 という、どちらも "服" というカテゴリなんですよね。
ということは・・・設計工夫できるかも！

**Comment by essences** [comment]
設計考慮中です。
ごしてきありがとうございます。。
次のスプリントで対応予定。
