### ISSUE TITLE
クラス名は、第三者が一目みて何を表しているか分かるようにしよう！

### ISSUE THREAD

**Issue by matap1623** [CentralsoftTrain2018/OchisCode#3]
掲題の通り。
クラス名に頻繁に出てくる "RecomXXX" は、おそらく "Recommend" のことだと思うけど、
それが分かっているのは作っているキミたちだけ！！

**Comment by essences** [comment]
はい、ありがとうございます。
そのほか、名詞辞書作ってとういつします。
