### ISSUE TITLE
Listの初期化タイミング

### ISSUE THREAD

**Issue by matap1623** [CentralsoftTrain2018/OchisCode#4]
Listを属性に持っているクラスについて、
① 全て属性定義部分で new している。つまり、該当クラスのインスタンス生成時には問答無用で Listは new される。
例えば、結局リストは使わなかったり、外から setterでセットする使い方だった場合、①の List は単なるメモリの無駄遣いだったことになるよね。

初期化のタイミングを工夫できそうだ・・・

**Comment by essences** [comment]
少なくとも、セッターは外す方向で検討。

データがない状態をどうするかの方針をきめる。
nullチェックのコストを考えて今回はつどnewのままいきます。

**Comment by essences** [comment]
良い情報ありがとう。
今後のソースはそのようにいたします。
