### ISSUE TITLE
(DAO系)実装レベル設計はしないのかな？

### ISSUE THREAD

**Issue by matap1623** [CentralsoftTrain2018/OchisCode#6]
DAO全般ですが、いきあたりばったり感を感じます。
進め方として「実装しながら直していこう！」というスタンスなのかな？
方針によりますが。

① どちらもDB連携のはずだが・・・
・RecomClothDao はDaoを継承してるが、UserClothDao は単独。

② DBコネクションオブジェクトあっちへこっちへ
・Dao は、自身で Connection を生成していながら、コンストラクタで外部から受け取るとはこれいかに？
・UserClothDao、RecomClothDao は、Connectionをコンストラクタで外部から受け取ったり、メソッドの引数として受け取ったり、はたまた、外からもらって親クラスに渡したり・・・

はちゃめちゃですな。
ちゃんと設計してから(頭にある程度のレベルで思い描ける状態)実装した方がいいんじゃないかなー？
まぁチーム方針によりますが。

**Comment by essences** [comment]
ずれがあったので、統一することとしました。
修正中です。
