### ISSUE TITLE
文字コード

### ISSUE THREAD

**Issue by CS-MakotoNinomiya** [CentralsoftTrain2018/OchisCode#8]
java7以降　文字コード用のクラスが追加されています。
その名は「StandardCharsets」
JavaDocによると、これらの文字セットは、Javaプラットフォームのあらゆる実装で使用できることが保証されています。とのこと。
自分で書くより間違いなく信頼できる。これを使わない手はない。

[RegistUserClothServlet.java#L41](https://github.com/CentralsoftTrain2018/OchisCode/blob/master/src/web/RegistUserClothServlet.java#L41)

ただし、HttpServletRequestのsetCharacterEncodingメソッドの引数はStringオブジェクトだ。

**Comment by essences** [comment]
良い情報ありがとう。
今後のソースはそのようにいたします。
